;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Gourd",DevComment="")
+GameplayTagList=(Tag="Action.Interacting",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.BlockedByTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.CantAffordCost",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.IsDead",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.MissingTags",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.Networking",DevComment="")
+GameplayTagList=(Tag="Activation.Fail.OnCooldown",DevComment="")
+GameplayTagList=(Tag="Buff.Heal.GourdAmount",DevComment="")
+GameplayTagList=(Tag="Camera.Player.Default",DevComment="플레이어 Follower Cam")
+GameplayTagList=(Tag="Data.CloudStep.InVisibleTime",DevComment="")
+GameplayTagList=(Tag="Effect.HitLevel.Frozen",DevComment="")
+GameplayTagList=(Tag="Effect.HitLevel.Normal",DevComment="")
+GameplayTagList=(Tag="Effect.HitLevel.Strong",DevComment="")
+GameplayTagList=(Tag="Effect.RemoveOnDeath",DevComment="")
+GameplayTagList=(Tag="Event.AOE.Sphere",DevComment="")
+GameplayTagList=(Tag="Event.Hustone.AitBlade",DevComment="")
+GameplayTagList=(Tag="Event.Hustone.AOE",DevComment="")
+GameplayTagList=(Tag="Event.Hustone.Stone",DevComment="")
+GameplayTagList=(Tag="Event.Hustone.Tornado",DevComment="")
+GameplayTagList=(Tag="Event.Launch.AirBlade",DevComment="")
+GameplayTagList=(Tag="Event.Launch.Tornado",DevComment="")
+GameplayTagList=(Tag="Event.Montage.End",DevComment="")
+GameplayTagList=(Tag="Event.Montage.NextSection",DevComment="")
+GameplayTagList=(Tag="Event.Shared.StartBattle",DevComment="")
+GameplayTagList=(Tag="Event.Task.EndTask",DevComment="")
+GameplayTagList=(Tag="Event.Task.StartAttack",DevComment="")
+GameplayTagList=(Tag="Event.Wukong.ConsumeGourd",DevComment="")
+GameplayTagList=(Tag="Event.Wukong.StartAddForce",DevComment="")
+GameplayTagList=(Tag="Event.Wukong.SwapGourdSoc",DevComment="")
+GameplayTagList=(Tag="Event.Wukong.Transform",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Buff.Heal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Default",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Enemy.Death",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Enemy.Debuff.Immobilize",DevComment="몬스터가 정지술에 걸릴 때")
+GameplayTagList=(Tag="GameplayCue.Status.Invisible",DevComment="")
+GameplayTagList=(Tag="Skill.Cooldown.Immobilize",DevComment="")
+GameplayTagList=(Tag="Skill.Stance.CanBeStoreFocusWhileDodge",DevComment="회피중 곤봉치 보류 가능성")
+GameplayTagList=(Tag="Skill.Stance.CanRunWhileCharge",DevComment="")
+GameplayTagList=(Tag="Skill.Stance.Parry",DevComment="간파")
+GameplayTagList=(Tag="State.AI.Attacking",DevComment="")
+GameplayTagList=(Tag="State.AI.Dead",DevComment="")
+GameplayTagList=(Tag="State.AI.Frozen",DevComment="")
+GameplayTagList=(Tag="State.AI.Idle",DevComment="")
+GameplayTagList=(Tag="State.AI.Investigating",DevComment="")
+GameplayTagList=(Tag="State.AI.Seeking",DevComment="")
+GameplayTagList=(Tag="State.Hit",DevComment="")
+GameplayTagList=(Tag="State.HuStone.Stoned",DevComment="")
+GameplayTagList=(Tag="Status.Dodge",DevComment="")
+GameplayTagList=(Tag="Status.Ganpha",DevComment="")
+GameplayTagList=(Tag="Status.PerfectDodge",DevComment="")

